//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyGen_20180405
    {
        public int ID { get; set; }
        public decimal EnergyGen_Value { get; set; }
        public System.DateTime EnergyGen_LatestUpdate { get; set; }
        public string EnergyGen_Weather { get; set; }
        public string EnergyGen_Wind_String { get; set; }
        public string EnergyGen_Solarradiation { get; set; }
        public string EnergyGen_UV { get; set; }
        public string EnergyGen_Forecast_Url { get; set; }
        public string EnergyGen_History_Url { get; set; }
        public string EnergyGen_Icon { get; set; }
        public string EnergyGen_Icon_Url { get; set; }
    }
}
