//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyPlantHist_20180405
    {
        public int Id { get; set; }
        public int PlantId { get; set; }
        public int EnergyGenId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
