//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int ID { get; set; }
        public int CountryID { get; set; }
        public int CompanyID { get; set; }
        public int PlantTypeID { get; set; }
        public int EnergyGenID { get; set; }
        public decimal Location_Latitude { get; set; }
        public decimal Location_Longitude { get; set; }
        public decimal Power_Gen { get; set; }
        public string Plant_Layout_Path { get; set; }
        public decimal Irradiation { get; set; }
        public decimal AMB_Temp { get; set; }
        public int SharedHolder_Id { get; set; }
        public decimal SharedHolder_Percentage { get; set; }
        public decimal Electricity_Gen { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual EnergyGen EnergyGen { get; set; }
        public virtual PlantType PlantType { get; set; }
        public virtual SharedHolder SharedHolder { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
