//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantEnergyGenHourlyView
    {
        public Nullable<long> Row { get; set; }
        public int PlantId { get; set; }
        public Nullable<decimal> AverageEnergyGenValue { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
    }
}
