//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantEnergyGenYearTarget
    {
        public Nullable<long> Row { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string YearTarget { get; set; }
        public int PlantId { get; set; }
    }
}
