//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plant()
        {
            this.EnergyPlantHists = new HashSet<EnergyPlantHist>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public int CompanyID { get; set; }
        public int PlantTypeID { get; set; }
        public decimal Location_Latitude { get; set; }
        public decimal Location_Longitude { get; set; }
        public decimal Power_Gen { get; set; }
        public string Plant_Layout_Path { get; set; }
        public decimal Irradiation { get; set; }
        public decimal AMB_Temp { get; set; }
        public int SharedHolder_Id { get; set; }
        public decimal SharedHolder_Percentage { get; set; }
        public decimal Electricity_Gen { get; set; }
        public int Customer_Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyPlantHist> EnergyPlantHists { get; set; }
        public virtual PlantType PlantType { get; set; }
        public virtual SharedHolder SharedHolder { get; set; }
    }
}
