//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plant()
        {
            this.EnergyPlantHists = new HashSet<EnergyPlantHist>();
            this.EnergyGenTargets = new HashSet<EnergyGenTarget>();
            this.EnergyGenDailies = new HashSet<EnergyGenDaily>();
            this.EnergyGenHourlies = new HashSet<EnergyGenHourly>();
            this.EnergyGenMonthlies = new HashSet<EnergyGenMonthly>();
            this.EnergyGenYearlies = new HashSet<EnergyGenYearly>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public int CompanyID { get; set; }
        public int PlantTypeID { get; set; }
        public decimal Location_Latitude { get; set; }
        public decimal Location_Longitude { get; set; }
        public decimal Power_Gen { get; set; }
        public string Plant_Layout_Path { get; set; }
        public decimal Irradiation { get; set; }
        public decimal AMB_Temp { get; set; }
        public int SharedHolder_Id { get; set; }
        public decimal SharedHolder_Percentage { get; set; }
        public decimal Electricity_Gen { get; set; }
        public int Customer_Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Order { get; set; }
        public string Location_Name { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string LatestTemperature { get; set; }
        public string TimeZone { get; set; }
        public double Power_Gen_Scale { get; set; }
        public double Power_Gen_Min { get; set; }
        public double Power_Gen_Max { get; set; }
        public double Irradiation_Scale { get; set; }
        public double Irradiation_Min { get; set; }
        public double Irradiation_Max { get; set; }
        public double AMB_Scale { get; set; }
        public double AMB_Min { get; set; }
        public double AMB_Max { get; set; }
        public string ForecastTemperature { get; set; }
        public int IsEnabled { get; set; }
        public string Cogen { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyPlantHist> EnergyPlantHists { get; set; }
        public virtual PlantType PlantType { get; set; }
        public virtual SharedHolder SharedHolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyGenTarget> EnergyGenTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyGenDaily> EnergyGenDailies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyGenHourly> EnergyGenHourlies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyGenMonthly> EnergyGenMonthlies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyGenYearly> EnergyGenYearlies { get; set; }
    }
}
