//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranImportCHPP
    {
        public int SeqNo { get; set; }
        public string W_avg { get; set; }
        public string POAI_avg { get; set; }
        public string Wh_sum { get; set; }
        public string TmpAmb_avg { get; set; }
        public string DataDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LatestUpdated { get; set; }
        public string SrcFileName { get; set; }
        public string Flag_Updated { get; set; }
        public Nullable<System.DateTime> DataDateTime_Hourly { get; set; }
        public Nullable<System.DateTime> DataDateTime_Parsed { get; set; }
        public Nullable<System.DateTime> DataDateTime_Daily { get; set; }
        public Nullable<System.DateTime> DataDateTime_Monthly { get; set; }
        public Nullable<System.DateTime> DataDateTime_Yearly { get; set; }
    }
}
