//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpscWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranLocu
    {
        public int SeqNo { get; set; }
        public string DataPoint { get; set; }
        public string DataValue { get; set; }
        public string DataDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FlagImport { get; set; }
        public string Id { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string Granularity { get; set; }
    }
}
